### ISSUE TITLE
Task: Rédiger descriptif de tâches de tri d’images

### ISSUE THREAD

**Issue by sjinko** [CUPUM/ai-edi-space#34]
# Task Description
Lors d’une discussion avec Hugo, il est apparu qu’une personne devra être affecté au tri d’image. Afin de recruter une personne (étudiant ou stagiaire) pour réaliser cette tache, @myriamgui, peux-tu rédiger une courte description des tâches qui seront imparties?

# List of actions
- [x] Action: Rédiger descriptif de tâche
- [x] Action: Définir à qui reviendra cette tache (étudiant auxiliaire ou stagiaire)

**Comment by myriamgui** [comment]
Le descriptif [ici](https://cirrus.gnp.umontreal.ca/index.php/s/kzx5xBJW7Tdr8YD)

Les tâches
•	Évaluation des images (sélection et rejet des images non représentatives d'un espace public)
•	Classification du corpus d’images selon le type de lieu (parc, square, rue)
•	Catégorisation des images selon des critères objectifs (présence de bancs, arbres, poubelles…)

**Comment by myriamgui** [comment]
Je ne suis pas certaine, cela dépend du nombre d'images, je dirais peut-être 10-15 heures. Qu'en penses-tu @hugobb ?

**Comment by hugobb** [comment]
Oui je pense que 10-15h cela devrait etre bon.

**Comment by sjinko** [comment]
@myriamgui Est-ce qu’on peut fermer ce issue?
